### ISSUE TITLE
Sorry for creating like that basically i tel l that if someone trade you apple x2 you get maintence and if you tried spawn apple you get maintence and alot fake apple version i understand that im wrong i know that i could use basic school of chaos classic note that in your readme

### ISSUE THREAD

**Issue by 7WQDXG** [DrNaN/DrNaN-Soc-Classic-Mod-V1#1]

**Comment by Cheeter541** [comment]
Ok

**Comment by 7WQDXG** [comment]
Also i wanna ask about spawner mod it does have paid version ? And how much or private ?

**Comment by Cheeter541** [comment]
No, it doesn't.

**Comment by 7WQDXG** [comment]
Oh okay

**Comment by 7WQDXG** [comment]
![Screenshot_20230502-220245.jpg](https://user-images.githubusercontent.com/104833781/235688929-6bfd2e53-1692-4bd6-b95a-54cf5ff19867.jpg)

Who this guy with having vnl of claw 300 - 330 and some alot items that its in level really high , and i dont undertstand how fu## you guys spawn the items without maintence that make sense we have outdated version or bad version of spawner

**Comment by 7WQDXG** [comment]
Dont mind about russian thing

**Comment by 7WQDXG** [comment]
wow *clap,clap,clap,clap,clap*

**Comment by 7WQDXG** [comment]
Also did you join server discord DevX Modding ?

**Comment by Cheeter541** [comment]
No. Can u text me on discord though?
